import { expect, test } from 'vitest';

import * as lib from './lib';

test('module exports', () => {
  expect({ ...lib }).toEqual({
    AG_GRID_JS_PACKAGE_NAME_PATTERN: lib.AG_GRID_JS_PACKAGE_NAME_PATTERN,
    AG_GRID_JS_UMD_GLOBAL_NAME: lib.AG_GRID_JS_UMD_GLOBAL_NAME,
    AngularGridApiBinding: lib.AngularGridApiBinding,
    GridApiDefinition: lib.GridApiDefinition,
    VueTemplateEngine: lib.VueTemplateEngine,
    VueTemplateFormatter: lib.VueTemplateFormatter,
    createVueAstNode: lib.createVueAstNode,
    findTemplateNodes: lib.findTemplateNodes,
    getAngularColumnApiReferences: lib.getAngularColumnApiReferences,
    getAngularGridApiReferences: lib.getAngularGridApiReferences,
    getColumnApiReferences: lib.getColumnApiReferences,
    getGridApiReferences: lib.getGridApiReferences,
    getJsGridApiReferences: lib.getJsGridApiReferences,
    getReactColumnApiReferences: lib.getReactColumnApiReferences,
    getReactGridApiReferences: lib.getReactGridApiReferences,
    getTemplateNodeChild: lib.getTemplateNodeChild,
    getVueColumnApiReferences: lib.getVueColumnApiReferences,
    getVueComponentComponentDeclarations: lib.getVueComponentComponentDeclarations,
    getVueComponentDataFieldReferences: lib.getVueComponentDataFieldReferences,
    getVueComponentTemplateProperty: lib.getVueComponentTemplateProperty,
    getVueComponentTemplateSource: lib.getVueComponentTemplateSource,
    getVueElementDirectives: lib.getVueElementDirectives,
    getVueElementEventHandlerDirectiveName: lib.getVueElementEventHandlerDirectiveName,
    getVueElementEventHandlerDirectives: lib.getVueElementEventHandlerDirectives,
    getVueGridApiReferences: lib.getVueGridApiReferences,
    getVueTemplateNodeChild: lib.getVueTemplateNodeChild,
    isColumnApiReference: lib.isColumnApiReference,
    isGridApiReference: lib.isGridApiReference,
    isPropertyAccessorNode: lib.isPropertyAccessorNode,
    isPropertyAssignmentNode: lib.isPropertyAssignmentNode,
    isPropertyInitializerNode: lib.isPropertyInitializerNode,
    isVueDirectiveAttribute: lib.isVueDirectiveAttribute,
    matchVueComponentMethod: lib.matchVueComponentMethod,
    matchers: lib.matchers,
    parseVueComponentTemplateSource: lib.parseVueComponentTemplateSource,
    parseVueSfcComponent: lib.parseVueSfcComponent,
    printTemplate: lib.printTemplate,
    removeTemplateNode: lib.removeTemplateNode,
    replaceTemplateNode: lib.replaceTemplateNode,
    transformFile: lib.transformFile,
    visitGridOptionsProperties: lib.visitGridOptionsProperties,
  });
});
