import { expect, test } from 'vitest';

import * as lib from './lib';

test('module exports', () => {
  expect({ ...lib }).toEqual({
    AG_GRID_JS_PACKAGE_NAME_PATTERN: lib.AG_GRID_JS_PACKAGE_NAME_PATTERN,
    AG_GRID_JS_UMD_GLOBAL_NAME: lib.AG_GRID_JS_UMD_GLOBAL_NAME,
    Angular: lib.Angular,
    AngularComponentTemplateDefinition: lib.AngularComponentTemplateDefinition,
    AngularGridApiBinding: lib.AngularGridApiBinding,
    AngularTemplateEngine: lib.AngularTemplateEngine,
    AngularTemplateFormatter: lib.AngularTemplateFormatter,
    createVueAstNode: lib.createVueAstNode,
    findNamedAngularTemplateElements: lib.findNamedAngularTemplateElements,
    findTemplateNodes: lib.findTemplateNodes,
    getAngularColumnApiReferences: lib.getAngularColumnApiReferences,
    getAngularComponentDataFieldReferences: lib.getAngularComponentDataFieldReferences,
    getAngularComponentDecoratorOptions: lib.getAngularComponentDecoratorOptions,
    getAngularComponentExternalTemplatePath: lib.getAngularComponentExternalTemplatePath,
    getAngularComponentMetadata: lib.getAngularComponentMetadata,
    getAngularGridApiReferences: lib.getAngularGridApiReferences,
    getAngularPropertyReadExpressionName: lib.getAngularPropertyReadExpressionName,
    getAngularTemplateNodeChild: lib.getAngularTemplateNodeChild,
    getAngularTemplateRootElements: lib.getAngularTemplateRootElements,
    getAngularViewChildMetadata: lib.getAngularViewChildMetadata,
    getColumnApiReferences: lib.getColumnApiReferences,
    getFrameworkEventNames: lib.getFrameworkEventNames,
    getGridApiReferences: lib.getGridApiReferences,
    getJsGridApiReferences: lib.getJsGridApiReferences,
    getReactColumnApiReferences: lib.getReactColumnApiReferences,
    getReactGridApiReferences: lib.getReactGridApiReferences,
    getTemplateNodeChild: lib.getTemplateNodeChild,
    getVueColumnApiReferences: lib.getVueColumnApiReferences,
    getVueComponentComponentDeclarations: lib.getVueComponentComponentDeclarations,
    getVueComponentDataFieldReferences: lib.getVueComponentDataFieldReferences,
    getVueComponentTemplateProperty: lib.getVueComponentTemplateProperty,
    getVueComponentTemplateSource: lib.getVueComponentTemplateSource,
    getVueElementDirectives: lib.getVueElementDirectives,
    getVueElementEventHandlerDirectiveName: lib.getVueElementEventHandlerDirectiveName,
    getVueElementEventHandlerDirectives: lib.getVueElementEventHandlerDirectives,
    getVueGridApiReferences: lib.getVueGridApiReferences,
    getVueTemplateNodeChild: lib.getVueTemplateNodeChild,
    GridApiDefinition: lib.GridApiDefinition,
    isColumnApiReference: lib.isColumnApiReference,
    isGridApiReference: lib.isGridApiReference,
    isNamedAngularMethodCallExpression: lib.isNamedAngularMethodCallExpression,
    isPropertyAccessorNode: lib.isPropertyAccessorNode,
    isPropertyAssignmentNode: lib.isPropertyAssignmentNode,
    isPropertyInitializerNode: lib.isPropertyInitializerNode,
    isVueDirectiveAttribute: lib.isVueDirectiveAttribute,
    matchers: lib.matchers,
    matchVueComponentMethod: lib.matchVueComponentMethod,
    parseAngularComponentTemplate: lib.parseAngularComponentTemplate,
    parseVueComponentTemplateSource: lib.parseVueComponentTemplateSource,
    parseVueSfcComponent: lib.parseVueSfcComponent,
    printTemplate: lib.printTemplate,
    removeTemplateNode: lib.removeTemplateNode,
    replaceTemplateNode: lib.replaceTemplateNode,
    transformFile: lib.transformFile,
    TSESTree: lib.TSESTree,
    updateAngularComponentTemplate: lib.updateAngularComponentTemplate,
    visitGridOptionsProperties: lib.visitGridOptionsProperties,
    VueTemplateEngine: lib.VueTemplateEngine,
    VueTemplateFormatter: lib.VueTemplateFormatter,
  });
});
