name: Verify PR branch

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch
        if: github.base_ref == 'release' && github.head_ref != 'main'
        run: |
          echo "ERROR: Only the 'main' branch can be merged to 'release'"
          exit 1
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get package version
        id: version
        run: |
          echo "VERSION=$(npm run --silent version)" >> $GITHUB_OUTPUT
      - name: Ensure new version
        run: |
          if [ $(git tag --list "${{ steps.version.outputs.VERSION }}") ]; then
            echo "ERROR: A release tag already exists for version ${{ steps.version.outputs.VERSION }}"
            exit 1
          fi
